# Generated by Django 4.0 on 2021-12-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant',
            new_name='participants',
        ),
    ]
